// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaRg0zHOiRweI2l8CuHAcAaeUstoUWPHA',
    appId: '1:323289127893:web:dac6277bb9521922bfbb5c',
    messagingSenderId: '323289127893',
    projectId: 'foodproject123-e4d89',
    authDomain: 'foodproject123-e4d89.firebaseapp.com',
    storageBucket: 'foodproject123-e4d89.appspot.com',
    measurementId: 'G-K1PXJ0NRCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtyD9sB8EJeOCUFvaA-up6DJVE7RTgy-o',
    appId: '1:323289127893:android:415f2613ef0868eabfbb5c',
    messagingSenderId: '323289127893',
    projectId: 'foodproject123-e4d89',
    storageBucket: 'foodproject123-e4d89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChh-7ESCmS_4-HYkiRrWqNLRWwB3C_bMM',
    appId: '1:323289127893:ios:3578c8ea9182a012bfbb5c',
    messagingSenderId: '323289127893',
    projectId: 'foodproject123-e4d89',
    storageBucket: 'foodproject123-e4d89.appspot.com',
    iosBundleId: 'com.example.bestFoodProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChh-7ESCmS_4-HYkiRrWqNLRWwB3C_bMM',
    appId: '1:323289127893:ios:50c87b7dd9ff7908bfbb5c',
    messagingSenderId: '323289127893',
    projectId: 'foodproject123-e4d89',
    storageBucket: 'foodproject123-e4d89.appspot.com',
    iosBundleId: 'com.example.bestFoodProject.RunnerTests',
  );
}
